# A more efficient and powerful way to define your CSS utilities.

# -----------------------------------------------------------------------------
# [static]
# For simple, one-off classes that have a single, unchanging CSS rule.
# Format: class-name = "css-rule"
# -----------------------------------------------------------------------------
[static]
flex           = "display: flex;"
border         = "border: 1px solid #e2e8f0;"
shadow         = "box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);"
h-full         = "height: 100%;"
w-full         = "width: 100%;"
items-center   = "align-items: center;"
justify-center = "justify-content: center;"
font-bold      = "font-weight: 700;"

# -----------------------------------------------------------------------------
# [dynamic]
# For classes that have a non-numeric or irregular scale. This is much cleaner now!
# Format: "prefix|css-property" = { suffix = "css-value", ... }
# Example: "text|font-size" with suffix "xl" generates ".text-xl { font-size: 1.25rem; }"
# -----------------------------------------------------------------------------
[dynamic]
"text|font-size" = { xs = "0.75rem", sm = "0.875rem", base = "1rem", lg = "1.125rem", xl = "1.25rem" }
"rounded|border-radius" = { sm = "0.125rem", md = "0.375rem", lg = "0.5rem", full = "9999px" }

# -----------------------------------------------------------------------------
# [generators]
# This is the super-powerful new part for your calculated styles!
# For classes that are generated from any number you want.
# Format: "prefix|css-property" = { multiplier = <number>, unit = "<css-unit>" }
#
# How it works:
# A class like "p-10" will be calculated as: 10 * multiplier, with the unit appended.
#
# Example with the 'p' rule below (where 1 unit = 0.25rem, or 4px):
# .p-4   -> padding: 1rem;   (because 4 * 0.25 = 1)
# .p-10  -> padding: 2.5rem;  (because 10 * 0.25 = 2.5)
# .p-100 -> padding: 25rem;   (because 100 * 0.25 = 25)
# -----------------------------------------------------------------------------
[generators]
"p|padding"         = { multiplier = 0.25, unit = "rem" }
"m|margin"          = { multiplier = 0.25, unit = "rem" }
"w|width"           = { multiplier = 0.25, unit = "rem" } # For rem-based width
"h|height"          = { multiplier = 0.25, unit = "rem" } # For rem-based height
"gap|gap"           = { multiplier = 0.25, unit = "rem" }
"top|top"           = { multiplier = 0.25, unit = "rem" }
"left|left"         = { multiplier = 0.25, unit = "rem" }
"right|right"       = { multiplier = 0.25, unit = "rem" }
"bottom|bottom"     = { multiplier = 0.25, unit = "rem" }
"text|font-size"    = { multiplier = 1, unit = "px" } # For arbitrary pixel sizes, e.g., .text-14
